name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash -l {0}

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: ipympl-dev
        environment-file: dev-environment.yml
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        auto-activate-base: false
        channels: conda-forge

    - name: Install ipympl
      run: |
        python -m build
        pip install dist/*.whl

    - name: Check installation files
      run: |
        test -d $CONDA_PREFIX/share/jupyter/nbextensions/jupyter-matplotlib
        test -f $CONDA_PREFIX/share/jupyter/nbextensions/jupyter-matplotlib/extension.js
        test -f $CONDA_PREFIX/share/jupyter/nbextensions/jupyter-matplotlib/index.js
        test -d $CONDA_PREFIX/share/jupyter/labextensions/jupyter-matplotlib
        test -f $CONDA_PREFIX/share/jupyter/labextensions/jupyter-matplotlib/package.json

    - name: Check nbextension and labextension
      run: |
        jupyter nbextension list 2>&1 | grep -ie "jupyter-matplotlib/extension.*enabled" -
        jupyter labextension list 2>&1 | grep -ie "jupyter-matplotlib.*enabled.*ok" -

    - name: Run tests
      run: pytest .

    - name: Test flake8
      run: flake8 ipympl --ignore=E501,W504,W503

    - name: Test TS linters
      run: |
        npm run eslint:check
        npm run prettier:check

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: ipympl-dev
        environment-file: dev-environment.yml
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        auto-activate-base: false
        channels: conda-forge

    - name: Build packages
      run: |
        python setup.py sdist bdist_wheel
        cd dist
        sha256sum * | tee SHA256SUMS

    - name: Upload builds
      uses: actions/upload-artifact@v2
      with:
        name: dist ${{ github.run_number }}
        path: ./dist

  install:
    runs-on: ${{ matrix.os }}-latest
    needs: [build]

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        python: ['3.6', '3.9']
        include:
          - python: '3.6'
            dist: 'ipympl*.tar.gz'
            jlab_version: 3
          - python: '3.9'
            dist: 'ipympl*.whl'
            jlab_version: 2.3.2

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          auto-activate-base: false
          channels: conda-forge

      - name: Install dependencies
        run: mamba install python=${{ matrix.python-version }} pip yarn jupyterlab=${{ matrix.jlab_version }} ipywidgets jupyter-packaging

      - uses: actions/download-artifact@v2
        with:
          name: dist ${{ github.run_number }}
          path: ./dist

      - name: Install the package
        run: |
          cd dist
          pip install -vv ${{ matrix.dist }}

      - name: Manually install labextension for lab2
        if: ${{ matrix.jlab_version }} == 2.3.2
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: jupyter labextension install --debug .

      - name: Test installation files
        run: |
          test -d $CONDA_PREFIX/share/jupyter/nbextensions/jupyter-matplotlib
          test -f $CONDA_PREFIX/share/jupyter/nbextensions/jupyter-matplotlib/extension.js
          test -f $CONDA_PREFIX/share/jupyter/nbextensions/jupyter-matplotlib/index.js
          test -d $CONDA_PREFIX/share/jupyter/labextensions/jupyter-matplotlib
          test -f $CONDA_PREFIX/share/jupyter/labextensions/jupyter-matplotlib/package.json
          test -d $CONDA_PREFIX/share/jupyter/labextensions/jupyter-matplotlib/static

      - name: Validate the nbextension
        run: jupyter nbextension list 2>&1 | grep "jupyter-matplotlib/extension"

      - name: Validate the labextension
        run: jupyter labextension list 2>&1 | grep jupyter-matplotlib


  visual-regression-tests:
    runs-on: ubuntu-latest
    needs: [build]

    strategy:
      fail-fast: false

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: "*"
          auto-activate-base: false
          channels: conda-forge

      - name: Install dependencies
        run: mamba install pip yarn jupyterlab=3.0.11 ipywidgets jupyter-packaging

      - uses: actions/download-artifact@v2
        with:
          name: dist ${{ github.run_number }}
          path: ./dist

      - name: Install the package
        run: pip install -vv ipympl*.whl
        working-directory: dist

      - name: Install test dependencies
        run: yarn install
        working-directory: ui-tests

      - name: Launch JupyterLab
        run: yarn run start-jlab:detached
        working-directory: ui-tests

      - name: Wait for JupyterLab
        uses: ifaxity/wait-on-action@v1
        with:
          resource: http-get://localhost:8888/api
          timeout: 20000

      - name: Run UI Tests
        run: yarn run test
        working-directory: ui-tests

      - name: Upload UI Test artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ui-test-output
          path: ui-tests/test-output
