name: Publish Package

on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Install dependencies
      run: |
        mamba install -c conda-forge python=3.9 jupyterlab yarn matplotlib ipywidgets jupyter-packaging=0.7
        pip install twine wheel build

    - name: Publish the Python package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m build
        twine upload dist/ipympl-*

    - name: Publish the NPM package
      run: |
        yarn install && yarn run build
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        PRE_RELEASE: ${{ github.event.release.prerelease }}
